config/routes.rb
Rails.application.routes.draw do
  resources :v2_needs
  resources :v1_needs
  resources :homes
  # root 'homes#index'
  root 'v1_needs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/v1_need.rb
class V1Need < ApplicationRecord
end

app/models/v2_need.rb
class V2Need < ApplicationRecord
end

app/models/v2_transaction.rb
class V2Transaction < ApplicationRecord
end

app/models/v2_user.rb
class V2User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :body)
    end
end

app/controllers/v1_needs_controller.rb
class V1NeedsController < ApplicationController
  before_action :set_v1_need, only: [:show, :edit, :update, :destroy]

  # GET /v1_needs
  # GET /v1_needs.json
  def index
    @v1_needs = V1Need.all
  end

  # GET /v1_needs/1
  # GET /v1_needs/1.json
  def show
  end

  # GET /v1_needs/new
  def new
    @v1_need = V1Need.new
  end

  # GET /v1_needs/1/edit
  def edit
  end

  # POST /v1_needs
  # POST /v1_needs.json
  def create
    @v1_need = V1Need.new(v1_need_params)

    respond_to do |format|
      if @v1_need.save
        format.html { redirect_to @v1_need, notice: 'V1 need was successfully created.' }
        format.json { render :show, status: :created, location: @v1_need }
      else
        format.html { render :new }
        format.json { render json: @v1_need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /v1_needs/1
  # PATCH/PUT /v1_needs/1.json
  def update
    respond_to do |format|
      if @v1_need.update(v1_need_params)
        format.html { redirect_to @v1_need, notice: 'V1 need was successfully updated.' }
        format.json { render :show, status: :ok, location: @v1_need }
      else
        format.html { render :edit }
        format.json { render json: @v1_need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /v1_needs/1
  # DELETE /v1_needs/1.json
  def destroy
    @v1_need.destroy
    respond_to do |format|
      format.html { redirect_to v1_needs_url, notice: 'V1 need was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_v1_need
      @v1_need = V1Need.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def v1_need_params
      params.require(:v1_need).permit(:user, :item, :budgeted, :allocated)
    end
end

app/controllers/v2_needs_controller.rb
class V2NeedsController < ApplicationController
  before_action :set_v2_need, only: [:show, :edit, :update, :destroy]

  # GET /v2_needs
  # GET /v2_needs.json
  def index
    @v2_needs = V2Need.all
  end

  # GET /v2_needs/1
  # GET /v2_needs/1.json
  def show
  end

  # GET /v2_needs/new
  def new
    @v2_need = V2Need.new
  end

  # GET /v2_needs/1/edit
  def edit
  end

  # POST /v2_needs
  # POST /v2_needs.json
  def create
    @v2_need = V2Need.new(v2_need_params)

    respond_to do |format|
      if @v2_need.save
        format.html { redirect_to @v2_need, notice: 'V2 need was successfully created.' }
        format.json { render :show, status: :created, location: @v2_need }
      else
        format.html { render :new }
        format.json { render json: @v2_need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /v2_needs/1
  # PATCH/PUT /v2_needs/1.json
  def update
    respond_to do |format|
      if @v2_need.update(v2_need_params)
        format.html { redirect_to @v2_need, notice: 'V2 need was successfully updated.' }
        format.json { render :show, status: :ok, location: @v2_need }
      else
        format.html { render :edit }
        format.json { render json: @v2_need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /v2_needs/1
  # DELETE /v2_needs/1.json
  def destroy
    @v2_need.destroy
    respond_to do |format|
      format.html { redirect_to v2_needs_url, notice: 'V2 need was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_v2_need
      @v2_need = V2Need.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def v2_need_params
      params.require(:v2_need).permit(:user, :item, :budgeted, :allocated, :purchased, :abandoned)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/v1_needs_helper.rb
module V1NeedsHelper
end

app/helpers/v2_needs_helper.rb
module V2NeedsHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.title %></td>
        <td><%= home.body %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @home.body %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HkNeeds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/v1_needs/_form.html.erb
<%= form_with(model: v1_need, local: true) do |form| %>
  <% if v1_need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(v1_need.errors.count, "error") %> prohibited this v1_need from being saved:</h2>

      <ul>
      <% v1_need.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item %>
  </div>

  <div class="field">
    <%= form.label :budgeted %>
    <%= form.number_field :budgeted %>
  </div>

  <div class="field">
    <%= form.label :allocated %>
    <%= form.number_field :allocated %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/v1_needs/edit.html.erb
<h1>Editing V1 Need</h1>

<%= render 'form', v1_need: @v1_need %>

<%= link_to 'Show', @v1_need %> |
<%= link_to 'Back', v1_needs_path %>

app/views/v1_needs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>V1 Needs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item</th>
      <th>Budgeted</th>
      <th>Allocated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @v1_needs.each do |v1_need| %>
      <tr>
        <td><%= v1_need.user %></td>
        <td><%= v1_need.item %></td>
        <td><%= v1_need.budgeted %></td>
        <td><%= v1_need.allocated %></td>
        <td><%= link_to 'Show', v1_need %></td>
        <td><%= link_to 'Edit', edit_v1_need_path(v1_need) %></td>
        <td><%= link_to 'Destroy', v1_need, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New V1 Need', new_v1_need_path %>

app/views/v1_needs/new.html.erb
<h1>New V1 Need</h1>

<%= render 'form', v1_need: @v1_need %>

<%= link_to 'Back', v1_needs_path %>

app/views/v1_needs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @v1_need.user %>
</p>

<p>
  <strong>Item:</strong>
  <%= @v1_need.item %>
</p>

<p>
  <strong>Budgeted:</strong>
  <%= @v1_need.budgeted %>
</p>

<p>
  <strong>Allocated:</strong>
  <%= @v1_need.allocated %>
</p>

<%= link_to 'Edit', edit_v1_need_path(@v1_need) %> |
<%= link_to 'Back', v1_needs_path %>

app/views/v2_needs/_form.html.erb
<%= form_with(model: v2_need, local: true) do |form| %>
  <% if v2_need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(v2_need.errors.count, "error") %> prohibited this v2_need from being saved:</h2>

      <ul>
      <% v2_need.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.number_field :user %>
  </div>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item %>
  </div>

  <div class="field">
    <%= form.label :budgeted %>
    <%= form.number_field :budgeted %>
  </div>

  <div class="field">
    <%= form.label :allocated %>
    <%= form.number_field :allocated %>
  </div>

  <div class="field">
    <%= form.label :purchased %>
    <%= form.datetime_select :purchased %>
  </div>

  <div class="field">
    <%= form.label :abandoned %>
    <%= form.datetime_select :abandoned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/v2_needs/edit.html.erb
<h1>Editing V2 Need</h1>

<%= render 'form', v2_need: @v2_need %>

<%= link_to 'Show', @v2_need %> |
<%= link_to 'Back', v2_needs_path %>

app/views/v2_needs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>V2 Needs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item</th>
      <th>Budgeted</th>
      <th>Allocated</th>
      <th>Purchased</th>
      <th>Abandoned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @v2_needs.each do |v2_need| %>
      <tr>
        <td><%= v2_need.user %></td>
        <td><%= v2_need.item %></td>
        <td><%= v2_need.budgeted %></td>
        <td><%= v2_need.allocated %></td>
        <td><%= v2_need.purchased %></td>
        <td><%= v2_need.abandoned %></td>
        <td><%= link_to 'Show', v2_need %></td>
        <td><%= link_to 'Edit', edit_v2_need_path(v2_need) %></td>
        <td><%= link_to 'Destroy', v2_need, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New V2 Need', new_v2_need_path %>

app/views/v2_needs/new.html.erb
<h1>New V2 Need</h1>

<%= render 'form', v2_need: @v2_need %>

<%= link_to 'Back', v2_needs_path %>

app/views/v2_needs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @v2_need.user %>
</p>

<p>
  <strong>Item:</strong>
  <%= @v2_need.item %>
</p>

<p>
  <strong>Budgeted:</strong>
  <%= @v2_need.budgeted %>
</p>

<p>
  <strong>Allocated:</strong>
  <%= @v2_need.allocated %>
</p>

<p>
  <strong>Purchased:</strong>
  <%= @v2_need.purchased %>
</p>

<p>
  <strong>Abandoned:</strong>
  <%= @v2_need.abandoned %>
</p>

<%= link_to 'Edit', edit_v2_need_path(@v2_need) %> |
<%= link_to 'Back', v2_needs_path %>